"""PlatformIO pre-build script.

- include/fw_version.h: firmware version with the git revision, rewritten only
  when it changes so unrelated builds are not invalidated.
- include/ead_secrets.h: created once with a random WPA2 passphrase for the
  device access point. Never committed (see .gitignore); read it to connect.
"""
import pathlib
import secrets
import subprocess

Import("env")  # noqa: F821 (provided by PlatformIO)

FW_VERSION = "0.1.0"
project = pathlib.Path(env["PROJECT_DIR"])  # noqa: F821
include = project / "include"


def git(*args):
    return subprocess.run(["git", *args], cwd=project, capture_output=True, text=True,
                          check=True).stdout.strip()


try:
    revision = git("rev-parse", "--short", "HEAD")
    dirty = git("status", "--porcelain", "--", ".")
    version = f"{FW_VERSION}+{revision}" + (".dirty" if dirty else "")
except (OSError, subprocess.CalledProcessError):
    version = f"{FW_VERSION}+nogit"

version_header = (
    "#pragma once\n"
    "// Generated by scripts/generate_headers.py at build time; not tracked.\n"
    f'#define EAD_FW_VERSION "{version}"\n'
)
version_path = include / "fw_version.h"
if not version_path.exists() or version_path.read_text() != version_header:
    version_path.write_text(version_header)

secrets_path = include / "ead_secrets.h"
if not secrets_path.exists():
    passphrase = secrets.token_urlsafe(12)
    secrets_path.write_text(
        "#pragma once\n"
        "// Generated once by scripts/generate_headers.py; not tracked. Keep private.\n"
        f'#define EAD_AP_PASSPHRASE "{passphrase}"\n'
    )
    print(f"Created {secrets_path} with a new Wi-Fi access point passphrase")
